services:
  pingvin-share:
    image: filedrop
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TRUST_PROXY=false # Set to true if a reverse proxy is in front of the container
    volumes:
      - "/opt/filedorp-data:/opt/app/backend/data"
      - "/opt/filedorp-data/images:/opt/app/frontend/public/img"
